### ISSUE TITLE
Redis connection robustness

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides3-autoupdate-service#36]
## redis flush

- stop everything to make a clean setup: flush redis, start the OS worker, start the AU service, reload the client
- do some autoupdates
- flush redis
- do one autoupdate: `Error: Can not receive new data: updating cache: updating hasPerm: key _config:lowest_change_id has wrong format. Expected id to be int not lowest_change_id`
- do a second one. This repeats like 20 times (I guess this depends on the time redis was not filled):
```
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 136383609067, to_change_id: 0, all_data: false}
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 0, to_change_id: 136383610157, all_data: true}
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 136383610157, to_change_id: 0, all_data: false}
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 0, to_change_id: 136383615272, all_data: true}
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 136383615272, to_change_id: 0, all_data: false}
[...]
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 136383629890, to_change_id: 0, all_data: false}
streaming-communication.service.ts:147 received {changed: {…}, deleted: {…}, from_change_id: 0, to_change_id: 136383630002, all_data: true}
```
The client does not make any requests in this time.
- if the flood is over, everything works fine

## redis not reachable on startup

If redis is not reachable this error appears: `Can not initialize data: get startdata from redis: get ready: dial tcp [::1]:6300: connect: connection refused`. In this case, this should be retried regularly (see next point).

## redis is not reachable during normal execution

It is good, that the service tries to reconnect, whichs works for small network issues (simulated with `CLIENT KILL TYPE normal`). But if the connection is offline for a longer time, the reconnection retries are spamming. Either do a fixed delay (e.g. one second) or a retry scheme like first 0.1 sec, 1 sec, 2 sec, and than every 5 sec. If redis comes back up everything works fine, this is very good.

**Comment by ostcar** [comment]
I fixed this issues. The last one is hard and I don't know if it is really fixed. For the `xread` requests it is. But not for the other requests.

For example: If an autoupdate is received in the wrong order (one autoupdate is missing) and immediately  afterwards redis stops, then the redis request to get the missing data will fail. It is hard to test this kind of race conditions.

**Comment by FinnStutzenstein** [comment]
The first one is not fixed. The error is gone, but the autoupdate flood still exists.

**Comment by ostcar** [comment]
@FinnStutzenstein #46 fixes the autoupdate-flood. But there is another issue.

After a redis flush and an autoupdate, the autoupdate-service gets a new change_id that is higher then the last change_id+1. So it fetches all keys, that have changed in between.

It does this by calling the redis command `ZRANGEBYSCORE change_id ($last_change_id $new_change_id-1`.
Since redis was flushed, there is no guarantee, that this will return all changed keys.

Another problem is, that the lowest change_id is saved in redis in the `change_id` key with the special field `_config:lowest_change_id`. The autoupdate service reads this fields on startup. There is currently no way to find out that redis was flushed and the value of this field has changed. This could result in unexpected behavior.

Maybe it would be a good idea, that the backend sends a signal to the autoupdate-service, when the cache was recreated. For example it could use this command:
```
XADD autoupdate * cache_recreated 1
```
If this happens, the autoupdate-service could reload all data and send a package with `all_data=true` to the clients.

**Comment by FinnStutzenstein** [comment]
> After a redis flush and an autoupdate, the autoupdate-service gets a new change_id that is higher then the last change_id+1. So it fetches all keys, that have changed in between.
> 
> It does this by calling the redis command `ZRANGEBYSCORE change_id ($last_change_id $new_change_id-1`.
> Since redis was flushed, there is no guarantee, that this will return all changed keys.

This s crrect, only the autoupdate should be send. If redis was flushed only the element ids from the autoupdate itself should be in the `change_id` key. The client handles inconsistent data (this is the current behavior), because it detects, if there is missing one resulting in querying all data.

> Another problem is, that the lowest change_id is saved in redis in the `change_id` key with the special field `_config:lowest_change_id`. The autoupdate service reads this fields on startup. There is currently no way to find out that redis was flushed and the value of this field has changed. This could result in unexpected behavior.

What unexpected behavior are you expecting, so where can be send wrong/... data?

> Maybe it would be a good idea, that the backend sends a signal to the autoupdate-service, when the cache was recreated. For example it could use this command:
> 
> ```
> XADD autoupdate * cache_recreated 1
> ```
> 
> If this happens, the autoupdate-service could reload all data and send a package with `all_data=true` to the clients.

I can do this. Does it replace the `cache_ready` flag? It is like a flag with a timestamp...

**Comment by ostcar** [comment]
> > After a redis flush and an autoupdate, the autoupdate-service gets a new change_id that is higher then the last change_id+1. So it fetches all keys, that have changed in between.
> > It does this by calling the redis command `ZRANGEBYSCORE change_id ($last_change_id $new_change_id-1`.
> > Since redis was flushed, there is no guarantee, that this will return all changed keys.
> 
> This s crrect, only the autoupdate should be send. If redis was flushed only the element ids from the autoupdate itself should be in the `change_id` key. The client handles inconsistent data (this is the current behavior), because it detects, if there is missing one resulting in querying all data.
I am not sure, if I understand you correctly.

Currently, it would send all keys in `change_id` but with the flag `all=false`. This means, that when an object was deleted shortly before the db-flush, the client will not be informed about it.

> > Another problem is, that the lowest change_id is saved in redis in the `change_id` key with the special field `_config:lowest_change_id`. The autoupdate service reads this fields on startup. There is currently no way to find out that redis was flushed and the value of this field has changed. This could result in unexpected behavior.
> 
> What unexpected behavior are you expecting, so where can be send wrong/... data?

If a client connects with a change_id that is lower then redis.lowest_change_id, but higher then autoupdate.lowest_change_id, then the autoupdate service does not send `all=true` but sends all keys in `change_id`. I think this will result in the same behavior as above, that a client does not get informed about deleted objects.

> > Maybe it would be a good idea, that the backend sends a signal to the autoupdate-service, when the cache was recreated. For example it could use this command:
> > ```
> > XADD autoupdate * cache_recreated 1
> > ```
> > 
> > 
> > If this happens, the autoupdate-service could reload all data and send a package with `all_data=true` to the clients.
> 
> I can do this. Does it replace the `cache_ready` flag? It is like a flag with a timestamp...
No. The `cache_ready` is still needed. When the autoupdate_service starts, it does not read old messages in the stream. Therefore the `cache_ready` key is needed for starting services. The `cache_recreated` field is needed for running services.

An alternative for `cache_ready` would be, that the worker guarantees, that the autoupdate-stream has only values, when the cache is ready. In this case, I could call `XREAD autoupdate - + COUNT 1` or `EXISTS autoupdate`.

**Comment by FinnStutzenstein** [comment]
> Currently, it would send all keys in `change_id` but with the flag `all=false`. This means, that when an object was deleted shortly before the db-flush, the client will not be informed about it.

This is correct. The change id will be much higher since the change_id generation rests on a cache flush -> The client will request all data and is up to date. Note: The client clears it's cache before injecting all data, so the missed deletion is no problem.

Regarding the other two things: I do not know what do you need explicitly. If you need e.g. something to raise your lowest change id, I can implement it.

**Comment by ostcar** [comment]
@FinnStutzenstein I implemented a reset() method. When a new change-ID is higher then 100 then the last change id, then all data is reset. It seems to work, but please test it as much as possible.

The change is in #46. You can checkout this branch an test it. I added a temporary commit to disable https. If you fixed the client/nodejs-proxy, to work with https, then I can merge #46.

**Comment by FinnStutzenstein** [comment]
Ok, seems to work. Can you make this value configurable with an environmentvariable?

**Comment by ostcar** [comment]
It this really necessary? I try to have as less config variables as possible. Why do you think, you would change this value?

**Comment by FinnStutzenstein** [comment]
We may have to tweek this value on massive amounts of autoupdates. With the old setup, a difference of 100 was likely possible, but II cannot say something about this new approach.
